import type { Metadata } from "next";
import "./globals.css";
import { Poppins as FontSans } from "next/font/google";
import Header from "@/components/Header";
import ConvexClientProvider from "./ConvexClientProvider";
import { Toaster } from "@/components/ui/toaster";
import SideNav from "@/components/SideNav";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fontSans.variable}>
        <Toaster />

        <ConvexClientProvider>
          <Header />
          <div className="flex min-h-screen">
            <SideNav />
            <main className="w-full">{children}</main>
          </div>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
